- name: Configure Basic Services on Ubuntu Desktop
  hosts: local
  gather_facts: true 
  roles:
    - common
    - desktop

  # vars_prompt:
  #   - name: ansible_become_password
  #     prompt: "sudo password"
  #     private: true